### ISSUE TITLE
Roboconf 2.0

### ISSUE THREAD

**Issue by rschiang** [sitcon-tw/roboconf#80]
This is a milestone tracking issue. The complete document could be found [here](https://hackmd.io/KYNhEYGMENOBaAJogrABngFkgdkvADjQCYAzeFRUgZgE570cAjNIA===?view).

### TODOs

- [ ] Pivot toward CRM, remove `issues`, `docs` app
- [ ] Remodel user data fields using EAV
- [ ] Use rules instead of builtin permission
- [ ] Neutralize community-specific features
- [ ] …
